title = "Willow Pigeon"
description = "Hi, I'm Willow. This is my digital shoebox—equal parts time capsule, portfolio, and proof I was here. I spend my days wrangling Kubernetes at Wealthsimple and my weekends tinkering with old files."
base_url = "https://noisypigeon.com"

compile_sass = false
generate_feeds = false
feed_filenames = ["posts_feed.xml"]
build_search_index = false

[extra]
avatar = "/assets/images/site/avatar.png"
social_preview = "/assets/images/site/social_preview.png"

[[extra.nav]]
title = "About"
link = "/pages/about"
order = 1

[[extra.nav]]
title = "GitHub"
link = "https://github.com/noisypigeon"
order = 2

[[extra.nav]]
title = "LinkedIn"
link = "https://www.linkedin.com/in/noisypigeon"
order = 3

[[extra.nav]]
title = "Unsplash"
link = "https://unsplash.com/@noisypigeon"
order = 4
