title = "Willow Graysen"
description = "Infra dev, data hoarder, mechanic-ish, photographer."
base_url = "https://noisypigeon.com"

compile_sass = false
generate_feeds = false
feed_filenames = ["posts_feed.xml"]
build_search_index = false

taxonomies = [
  { name = "tags", feed = false },
]

[extra]
avatar = "/assets/images/site/avatar.png"
social_preview = "/assets/images/site/social_preview.png"

[[extra.nav]]
title = "About"
link = "/pages/about"
order = 1

[[extra.nav]]
title = "GitHub"
link = "https://github.com/noisypigeon"
order = 2

[[extra.nav]]
title = "LinkedIn"
link = "https://www.linkedin.com/in/noisypigeon"
order = 3

[[extra.nav]]
title = "Unsplash"
link = "https://unsplash.com/@noisypigeon"
order = 4
